name: Go

on:
  push:
    branches: [ master ]
#  pull_request:
#    branches: [ master ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.17

    - name: Build
      run: go build -v ./...

    - name: Test
      run: go test -v ./...

    - name: Create Tag
      run: |
        git tag v0.0.${{ github.run_number }}
        git push https://fox-md:$GH_TOKEN@github.com/$GITHUB_REPOSITORY v0.0.${{ github.run_number }}
